/**
 * Location domain types — the backbone of the programmatic local-SEO engine.
 *
 * Design notes:
 * - A single `Location` shape represents every level of the Polish
 *   administrative hierarchy (voivodeship / powiat / gmina / city / village).
 *   `unitType` discriminates the level; hierarchy is expressed via parent
 *   slugs so the tree can be re-linked without rewriting every node.
 * - Nothing here is content. Locations carry *facts* (names, hierarchy,
 *   population, seo control flags). Actual page copy is generated by the
 *   content layer using this data as input — see /lib/seo and future
 *   /lib/content.
 * - This is intentionally framework-agnostic and serializable so it can
 *   later move from static TS modules to Supabase/CMS without changing
 *   consumers.
 */

export type AdministrativeUnitType =
  | "wojewodztwo" // voivodeship (16 total)
  | "powiat" // powiat / miasto na prawach powiatu (~380 total)
  | "gmina" // commune
  | "miasto" // city / town
  | "miejscowosc"; // smaller locality / village

/** SEO rollout tier. Controls build/publish order per spec §43. */
export type SeoTier = "A" | "B" | "C" | "long-tail";

/** Editorial/publishing status of a location page. */
export type ContentStatus =
  | "not_started" // no dedicated content yet, page not built
  | "draft" // content being prepared
  | "published" // live and intended to be indexed
  | "thin" // live but flagged as low-value, kept noindex until improved
  | "retired"; // intentionally removed / redirected

export interface GeoCoordinates {
  lat: number;
  lng: number;
}

export interface SeoControl {
  /** Whether this location is eligible to be indexed by search engines. */
  indexable: boolean;
  /** Explicit robots directive; derived from `indexable` unless overridden. */
  robots?: "index,follow" | "noindex,follow" | "noindex,nofollow";
  /** Canonical URL override. Defaults to the location's own URL. */
  canonicalPath?: string;
  /** Whether to include this location in the generated sitemap. */
  inSitemap: boolean;
  /** Editorial status gating whether the page is considered "ready". */
  contentStatus: ContentStatus;
}

export interface Location {
  /** Stable unique identifier, independent of slug (slugs may change). */
  locationId: string;

  /** Display name, e.g. "Kraków", "Małopolskie". */
  name: string;
  /** Locative / grammatical form used in copy, e.g. "w Krakowie" — TODO fill per location. */
  nameLocative?: string;

  slug: string;
  unitType: AdministrativeUnitType;

  /** Parent references by slug — null at the top of the tree (wojewodztwo). */
  wojewodztwoSlug: string | null;
  powiatSlug: string | null;
  gminaSlug: string | null;

  /** Human-readable region label used in copy, e.g. "Małopolska", "Śląsk". */
  region: string | null;

  /** Population, when publicly known. Leave undefined rather than guessing. */
  population?: number;
  /** Where the population figure came from, for future verification. */
  populationSource?: string;

  coordinates?: GeoCoordinates;

  /** Slugs of neighboring locations at the same unitType, closest first. */
  neighborSlugs: string[];
  /** Slug of the larger reference city in the region (for "nearby" framing). */
  largerCitySlug?: string;

  /** Does Aga actually serve this location? Must never default to true blindly. */
  agaServesLocation: boolean;

  seoPriority: number; // 1 (highest) - 100 (lowest), manual editorial weight
  tier: SeoTier;

  seo: SeoControl;

  /** Fully-qualified path this location resolves at, e.g. "/thermomix/krakow". */
  urlPath: string;

  /** Free-form local facts an editor has actually confirmed (never fabricated). */
  localFacts?: string[];

  createdAt: string;
  updatedAt: string;
}

/** Convenience shape for rendering breadcrumb trails. */
export interface LocationBreadcrumb {
  label: string;
  href: string;
}

/** Result of resolving a URL slug path against the location engine. */
export interface LocationResolution {
  location: Location;
  wojewodztwo: Location | null;
  powiat: Location | null;
  breadcrumbs: LocationBreadcrumb[];
  neighbors: Location[];
}
